### ISSUE TITLE
Interfejs przyjazny dla użytkownika

### ISSUE THREAD

**Issue by kazimierz-256** [kazimierz-256/ConcurrentScenario#22]
Mam nadzieję żę te zmiany w GUI polepszą odbiór przez prowadzącą:

* powiększyć czcionkę
* aplikacja ma być "starego typu" - taka, że wasza babcia by ją obsłużyła;). Rezygnujemy z dynamicznie dodawanych pól, na korzyść przycisków `new` (np dla akcji w scenariuszu) i `save` zeby potwierdzic. Ja to widze tak: Mamy nasz formularz, który wygląda mega podobnie do naszego, ale jest bardziej zbity i aby go edytować należy kliknąć przycisk `edit` przy danym polu. Po Kliknięciu przycisku `edit` pokazuje nam się pole do wpisania tekstu - jesli to domena akcji to tak jak jest teraz, jeśli akcje/obserwacje w scenariuszu to mamy dodatkowo przyciski "dodaj nowy", ktore powoduja wyskoczenie nowego pola, zamiast dynamicznego pojawiania sie nowego pola. Wazne zeby aktualnie edytowane pole wyroznialo sie jakos od juz wypelnionych pol. Na koniec edycji nalezy kliknac przycisk `save`, i tez widac ze on dziala (np tekst sie wyszarza czy cos).
* aktualizacja vuejsowego stanu na onkeyup zamiast domyślne ondefocus czy onsubmit cokolwiek to jest
* ukryć pole DEBUG
* domyślnie pola powinny być prefilled historyjką simply czy tego typu prostą

**Comment by brooda** [comment]
Wydaje mi się, że to "at time..." jest zdecydowanie za mało widoczne. 
![image](https://user-images.githubusercontent.com/13292836/59067563-42ee9900-88b2-11e9-83fd-f4a355b7ab78.png)

Można po prostu taką jakby tabelkę: po lewej jest "TIME 0", "TIME 1"... DUŻYMI LITERAMI, a po prawj pola do wpisywania akcji.

**Comment by kazimierz-256** [comment]
Proszę aby (main.js) obiekt VueJSowy form > obiekt data (modelData) > pole answer był ustawiany na undefined jak tylko użytkownik zrobi onkeydown w jakimklowiek inpucie @bulkaaa. Poza tym nie działa defocus w akcjach i pewnie gdzieś jeszcze.

**Comment by NotTakenValidName** [comment]
@kazimierz-256 Ukryłem debug, powiększyłem czcionke, przeniosłem napis mówiący o czasie obserwacji i powiększyłem go, poprzesuwałem elementy na stornie żeby było bardizej kompaktowo, dodałem komunikaty mówiące o tym jak obsługiwać sekcję z akcjami i obserwacjami - ich nie będę kastrował - powołuję się na klauzulę sumienia. Przycisk save nie ma tutaj sensu - wszystko jest cały czas 'zapisane'.
@bulkaaa zostało jeszcze ustawić domyślny stan strony na wypełniony jakąś historyjką i postprawdzać gdzie sie stan nie resetuje przy inpucie
