### ISSUE TITLE
logic_tree_parsing:logic_tree_from_text does not parse fluents with `_` correctly

### ISSUE THREAD

**Issue by olabknbit** [kazimierz-256/ConcurrentScenario#25]
While I was working on #24, I tried to create a Domain from:
```
Domain_Text = 'BUY causes OWN_TV or not OWN_TV
        WATCH1 causes HAPPY if OWN_TV
        WATCH2 causes not HAPPY if not OWN_TV
        STEAL causes OWN_TV if not OWN_TV'
```
But `logic_tree_parsing:logic_tree_from_text` would fail and not return a valid "effect part" for the first line of domain (`OWN_TV or not OWN_TV`). 
Renaming `OWN_TV` to `OwnTv` resolved the errors, but I think the parser should work for underscores. 

Do you agree @kazimierz-256 ?

I tried debugging it, but it seems that it is not parsed correctly by the `-->` operator with which I am not familiar.

**Comment by kazimierz-256** [comment]
Parsing does not allow underscores. Everything works as expected.

**Comment by kazimierz-256** [comment]
I will enable underscores in a pull request
