### ISSUE TITLE
Add checks for functionality introduced in #29

### ISSUE THREAD

**Issue by olabknbit** [kazimierz-256/ConcurrentScenario#30]
Please add unit tests for functionality introduced in #29

**Comment by kazimierz-256** [comment]
Heyyy in the very same pull request I have added some initial *passing* tests for this functionality. Could you please (or someone) **transform this file into a proper test file/component .plt**? Warsaw standoff passess with flying colours when added IDLE action to its domain (works all the way from the user input)
