### ISSUE TITLE
Add new story

### ISSUE THREAD

**Issue by kazimierz-256** [kazimierz-256/ConcurrentScenario#38]
Soup spilling story:
PickUpL causes HoldingL and (HoldingR iff not Spilled)
PickUpR causes HoldingR and (HoldingL iff not Spilled)

...so it is possible to implement soup story

**Comment by olabknbit** [comment]
@swasilkowski prosze jeszcze to przetestuj :) kilka testow

**Comment by kazimierz-256** [comment]
To powinno być tak: PickUpL causes HoldingL, PickUpR causes HoldingR oraz w scenariuszu taka sprytna obserwacja w chwili następnej (not Spilled iff HoldingL and HoldingR). Inaczej nieporządane fluenty należałyby niechcący do okluzji, ale koniec końców udało się! Da się zaimplementować tę historyjkę!
