### ISSUE TITLE
Update js prescribed story for warsaw standoff

### ISSUE THREAD

**Issue by olabknbit** [kazimierz-256/ConcurrentScenario#42]
Please update javascript prescribed story of warsaw standoff so that it is identical to the `.pl` one, if it is not already.

If they are identical, simply say so and close this issue.

**Comment by brooda** [comment]
I take this. Will be approx. in 3h.

**Comment by brooda** [comment]
Generalnie, to się wszystko zgadza. Tylko, czy ma być IDLE w tej historyjce?

**Comment by olabknbit** [comment]
mozesz dodac testy do `user_input_tests.plt` ktore sprawdzaja czy jak nie jest wpisane IDLE w historyjce to w mimo wszystko dziala jak powinno? jak cos nie bedzie dzialac to poprawie. Powinno dzialac bez wpisywania IDLE w historyjce ale daj testy zeby na 100 pro byc pewnym @brooda 

Dzieki!

**Comment by brooda** [comment]
Nie chodziło Ci o `user_input_parsing`?
